export const nonCapitalCities: string[] = [
  "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Miami",
  "Toronto", "Vancouver", "Montreal", "Calgary",
  "Guadalajara", "Monterrey", "Puebla", "Tijuana",
  "Rio de Janeiro", "São Paulo", "Salvador", "Fortaleza", "Belo Horizonte",
  "Medellin", "Cali", "Barranquilla", "Cartagena",
  "Arequipa", "Trujillo", "Chiclayo", "Iquitos",
  "Córdoba", "Rosario", "Mendoza", "La Plata",
  "Manchester", "Birmingham", "Liverpool", "Glasgow", "Edinburgh",
  "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg",
  "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Dusseldorf",
  "Milan", "Naples", "Turin", "Palermo", "Genoa", "Florence",
  "Barcelona", "Valencia", "Seville", "Zaragoza", "Málaga",
  "Porto", "Funchal", "Braga", "Setúbal",
  "Thessaloniki", "Patras", "Larissa", "Heraklion", "Volos",
  "Rotterdam", "Geneva", "Zurich", "Krakow", "Gothenburg", "Saint Petersburg",
  "Ghent", "Antwerp", "Salzburg",
  "Yokohama", "Osaka", "Nagoya", "Sapporo", "Kobe", "Kyoto",
  "Shanghai", "Guangzhou", "Shenzhen", "Chongqing", "Chengdu", "Tianjin", "Wuhan",
  "Mumbai", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata",
  "Busan", "Incheon", "Daegu",
  "Ho Chi Minh City", "Da Nang", "Hai Phong", "Can Tho",
  "Chiang Mai", "Pattaya", "Phuket", "Khon Kaen",
  "Penang", "Johor Bahru", "Ipoh", "Kuching",
  "Surabaya", "Bandung", "Medan", "Semarang",
  "Lahore", "Karachi", "Faisalabad", "Rawalpindi",
  "Jeddah", "Mecca", "Medina", "Dammam",
  "Dubai", "Sharjah", "Al Ain", "Ajman",
  "Istanbul", "Izmir", "Bursa", "Antalya",
  "Durban", "Johannesburg", "Cape Town",
  "Mombasa", "Kisumu", "Nakuru", "Eldoret",
  "Lagos", "Kano", "Ibadan", "Kaduna", "Port Harcourt",
  "Casablanca", "Fes", "Marrakech", "Tangier",
  "Kumasi", "Tamale", "Sekondi-Takoradi", "Cape Coast",
  "Alexandria", "Khartoum", "Dakar", "Luanda",
  "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide",
  "Auckland", "Christchurch", "Hamilton", "Tauranga"
];

export const capitalCities: Record<string, string> = {
  "Paris": "France", "Berlin": "Germany", "Rome": "Italy",
  "Madrid": "Spain", "Lisbon": "Portugal", "Athens": "Greece",
  "London": "United Kingdom", "Oslo": "Norway", "Stockholm": "Sweden",
  "Helsinki": "Finland", "Copenhagen": "Denmark", "Vienna": "Austria",
  "Brussels": "Belgium", "Amsterdam": "Netherlands", "Dublin": "Ireland",
  "Warsaw": "Poland", "Budapest": "Hungary", "Bucharest": "Romania",
  "Sofia": "Bulgaria", "Zagreb": "Croatia", "Ljubljana": "Slovenia",
  "Bratislava": "Slovakia", "Prague": "Czech Republic", "Belgrade": "Serbia",
  "Sarajevo": "Bosnia and Herzegovina", "Podgorica": "Montenegro",
  "Tirana": "Albania", "Valletta": "Malta", "Nicosia": "Cyprus",
  "Reykjavik": "Iceland", "Kiev": "Ukraine", "Minsk": "Belarus",
  "Vilnius": "Lithuania", "Riga": "Latvia", "Tallinn": "Estonia",
  "Luxembourg": "Luxembourg", "Bern": "Switzerland", "Chisinau": "Moldova",
  "Skopje": "North Macedonia", "Pristina": "Kosovo", "Vatican City": "Vatican City",
  "Washington, D.C.": "United States", "Ottawa": "Canada", "Mexico City": "Mexico",
  "Havana": "Cuba", "Santo Domingo": "Dominican Republic", "San Salvador": "El Salvador",
  "Guatemala City": "Guatemala", "Tegucigalpa": "Honduras", "Managua": "Nicaragua",
  "San José": "Costa Rica", "Panama City": "Panama", "Kingston": "Jamaica",
  "Nassau": "Bahamas", "Port-au-Prince": "Haiti", "San Juan": "Puerto Rico",
  "Brasília": "Brazil", "Buenos Aires": "Argentina", "Lima": "Peru",
  "Santiago": "Chile", "Bogotá": "Colombia", "Quito": "Ecuador",
  "Caracas": "Venezuela", "Sucre": "Bolivia", "Asunción": "Paraguay",
  "Montevideo": "Uruguay", "Georgetown": "Guyana", "Paramaribo": "Suriname",
  "Tokyo": "Japan", "Beijing": "China", "New Delhi": "India",
  "Seoul": "South Korea", "Bangkok": "Thailand", "Kuala Lumpur": "Malaysia",
  "Jakarta": "Indonesia", "Singapore": "Singapore", "Ankara": "Turkey",
  "Riyadh": "Saudi Arabia", "Abu Dhabi": "United Arab Emirates", "Tehran": "Iran",
  "Baghdad": "Iraq", "Jerusalem": "Israel", "Yerevan": "Armenia",
  "Baku": "Azerbaijan", "Tbilisi": "Georgia", "Hanoi": "Vietnam",
  "Phnom Penh": "Cambodia", "Vientiane": "Laos", "Manila": "Philippines",
  "Kathmandu": "Nepal", "Colombo": "Sri Lanka", "Dhaka": "Bangladesh",
  "Islamabad": "Pakistan", "Kabul": "Afghanistan", "Tashkent": "Uzbekistan",
  "Doha": "Qatar", "Kuwait City": "Kuwait", "Beirut": "Lebanon", "Amman": "Jordan",
  "Muscat": "Oman", "Manama": "Bahrain", "Damascus": "Syria", "Pyongyang": "North Korea",
  "Cairo": "Egypt", "Pretoria": "South Africa", "Nairobi": "Kenya",
  "Rabat": "Morocco", "Accra": "Ghana", "Abuja": "Nigeria",
  "Algiers": "Algeria", "Tunis": "Tunisia", "Dakar": "Senegal",
  "Addis Ababa": "Ethiopia", "Tripoli": "Libya", "Lusaka": "Zambia",
  "Harare": "Zimbabwe", "Kigali": "Rwanda",
  "Canberra": "Australia", "Wellington": "New Zealand", "Suva": "Fiji",
  "Port Moresby": "Papua New Guinea", "Honiara": "Solomon Islands",
  "Hong Kong": "Hong Kong", "Macau": "Macau", "Taipei": "Taiwan"
};
